// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO5wcrNvea_vp_zfxPckhWxs8tpoJ8IFA',
    appId: '1:355034620973:web:5873ec1d2c485844e544a4',
    messagingSenderId: '355034620973',
    projectId: 'flutter-e-commerce-riverpod',
    authDomain: 'flutter-e-commerce-riverpod.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-riverpod.appspot.com',
    measurementId: 'G-9YV1P82N0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDraG_wv8Lsn85QRUiPMzzrv6gaVXq2Evk',
    appId: '1:355034620973:android:c8163c4a234fcdbae544a4',
    messagingSenderId: '355034620973',
    projectId: 'flutter-e-commerce-riverpod',
    storageBucket: 'flutter-e-commerce-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrEJ0wdcV4y7Evb0D29UKvBfLBneVdyn4',
    appId: '1:355034620973:ios:01f795fbfe8935c0e544a4',
    messagingSenderId: '355034620973',
    projectId: 'flutter-e-commerce-riverpod',
    storageBucket: 'flutter-e-commerce-riverpod.appspot.com',
    iosClientId: '355034620973-t593l3cbg8k5og0hvost1vkakiouqhhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceAppWithFirebaseRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrEJ0wdcV4y7Evb0D29UKvBfLBneVdyn4',
    appId: '1:355034620973:ios:01f795fbfe8935c0e544a4',
    messagingSenderId: '355034620973',
    projectId: 'flutter-e-commerce-riverpod',
    storageBucket: 'flutter-e-commerce-riverpod.appspot.com',
    iosClientId: '355034620973-t593l3cbg8k5og0hvost1vkakiouqhhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceAppWithFirebaseRiverpod',
  );
}
